### PR TITLE
Support image lists from file

### PR DESCRIPTION
**Pull request by stweil**
Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by stweil** [comment]
With this commit, the list of images which is used for training or evaluation can be read from a file: `--train.images @FILELIST` reads the image filenames from file `FILELIST`.

**Comment by ChWick** [comment]
There should already be support for this, unfortunately this is not tested, not in the docs, ... (see https://github.com/Calamari-OCR/calamari/blob/15afa2988f9709a7f99b2ab5b3f7259b48cee2cf/calamari_ocr/utils/glob.py#L9)

It should be possible to just include a `NAME.files` file, that will be automatically parsed

**Comment by stweil** [comment]
> It should be possible to just include a `NAME.files` file, that will be automatically parsed

Nice, I'll give that a try.

**Comment by stweil** [comment]
@ChWick, the new code works for `calamari-train`, but fails for  `calamari-eval`:

```
calamari-eval --gt.texts list.files
INFO     2021-10-01 22:29:52,933 calamari_ocr.ocr.dataset.datar: Resolving input files
INFO     2021-10-01 22:29:56,304 calamari_ocr.ocr.dataset.datar: Resolving input files
Loading Prediction: 0it [00:00, ?it/s]
INFO     2021-10-01 22:29:56,833     calamari_ocr.ocr.evaluator: 4810/4810 lines could not be matched during the evaluation.
CRITICAL 2021-10-01 22:29:56,833             tfaip.util.logging: Uncaught exception
Traceback (most recent call last):
  File "/venv/bin/calamari-eval", line 33, in <module>
    sys.exit(load_entry_point('calamari-ocr==2.1.3', 'console_scripts', 'calamari-eval')())
  File "/venv/lib/python3.7/site-packages/calamari_ocr-2.1.3-py3.7.egg/calamari_ocr/scripts/eval.py", line 200, in run
    main(parse_args())
  File "/venv/lib/python3.7/site-packages/calamari_ocr-2.1.3-py3.7.egg/calamari_ocr/scripts/eval.py", line 228, in main
    r = evaluator.run(gt_dataset=args.gt, pred_dataset=pred_data)
  File "/venv/lib/python3.7/site-packages/calamari_ocr-2.1.3-py3.7.egg/calamari_ocr/ocr/evaluator.py", line 99, in run
    return self.evaluate(gt_data=gt_data, pred_data=pred_data)
  File "/venv/lib/python3.7/site-packages/calamari_ocr-2.1.3-py3.7.egg/calamari_ocr/ocr/evaluator.py", line 218, in evaluate
    f"No lines could be matched by their ID. First 10 gt ids "
ValueError: No lines could be matched by their ID. First 10 gt ids ['line1'], first 10 pred ids []
```

So it correctly expands the gt ids from `list.files` which for this test contains a single file `line1.gt.txt`, but fails to use that expanded list for the pred ids.

**Comment by ChWick** [comment]
@stweil  The current `calamari/2.1` got a update that should fix it. I will merge it in the master if all tests pass. Thanks for reporting

**Pull request closed without merging**
